/** Main narration stays brief; chapter notes hold mechanisms, evidence and limits. */
export const SOURCES = {
  internet: { title: 'Internet Society · A brief history, by its builders', url: 'https://www.internetsociety.org/internet/history-internet/brief-history-internet/' },
  web: { title: 'CERN · The birth of the Web', url: 'https://home.cern/science/computing/the-birth-of-the-web/' },
  money: { title: 'Bank of England · How money is created', url: 'https://www.bankofengland.co.uk/explainers/how-is-money-created' },
  surveillance: { title: 'FTC · A Look Behind the Screens (2024)', url: 'https://www.ftc.gov/reports/look-behind-screens-examining-data-practices-social-media-video-streaming-services' },
  wellbeing: { title: 'Allcott et al. · The Welfare Effects of Social Media', url: 'https://www.nber.org/papers/w25514' },
  politics: { title: 'Nyhan et al. · Like-minded sources on Facebook (2023)', url: 'https://www.nature.com/articles/s41586-023-06297-w' },
  ai: { title: 'FTC · AI partnerships and investments (2025)', url: 'https://www.ftc.gov/reports/ftc-staff-report-ai-partnerships-investments-6b-study' },
  protocol: { title: 'AT Protocol · Architecture and portability', url: 'https://atproto.com/guides/overview' },
};
export type SourceKey = keyof typeof SOURCES;
export type Chapter = { id: string; act: string; chapter: string; title: string; body: string; scene: number; action: string; note: string; sources: SourceKey[]; mechanism: string };
export const BEATS: Chapter[] = [
  { id:'connection', act:'Origins', chapter:'Connection', title:'Another web\nis possible.', body:'The internet began with a beautiful idea. People could connect directly. The network belonged to everyone.', scene:0, action:'', mechanism:'', note:'The opening expresses an ideal, not a claim that access or ownership was ever equal. Governments, universities, companies and communities built the internet. Its distinctive possibility was that independent networks could communicate through shared rules.', sources:['internet'] },
  { id:'packets', act:'Origins', chapter:'Networks of networks', title:'No single center.\nMany ways through.', body:'Messages became packets of light. Separate networks learned a shared language. A university, a laboratory, a person at home: different worlds could finally reach one another.', scene:.20, action:'Send a packet', mechanism:'Independent networks · shared rules', note:'Packets are pieces of data, not literal light in every medium. TCP/IP lets networks interoperate without requiring identical hardware or a single operator. Routes can change; delivery still depends on working infrastructure. The illustration compresses decades of development into a landscape of connected places.', sources:['internet'] },
  { id:'open-web', act:'Origins', chapter:'The open Web', title:'A link was\nan open door.', body:'Then came the Web. Pages linked to pages. People published, discovered, and built on each other’s work. In 1993, CERN released the Web software into the public domain. Permission was no longer the starting point.', scene:.42, action:'', mechanism:'Publish · link · discover', note:'The Web is one service on the internet, not the internet itself. Its shared conventions let independently hosted pages link across organizations. Open publishing did not remove inequalities of access, hosting costs or moderation needs; it widened who could build.', sources:['web'] },
  { id:'capture', act:'Enclosure', chapter:'The convenient middle', title:'Then the middle\nmoved in.', body:'Search helped us find. Social feeds helped us gather. Marketplaces helped us trade. Useful services became the places everyone needed to be. Each new arrival made the center more valuable.', scene:.88, action:'', mechanism:'More people → more reasons to stay', note:'Network effects can create real value: a service is often more useful when others participate. The problem arises when that value is difficult to carry elsewhere. This chapter is a model of platform dependence, not a claim that every large service has the same business model.', sources:[] },
  { id:'enclosure', act:'Enclosure', chapter:'Relationships behind walls', title:'Open roads.\nPrivate gates.', body:'The internet’s shared roads remained. But our identities, audiences, and histories settled inside private platforms. Leaving an app could mean leaving the people we came for. Connection became a source of control.', scene:1.35, action:'', mechanism:'The network stays open. The relationship gets enclosed.', note:'The distinction is between layers. Open transport protocols do not require applications to offer portable accounts, interoperable social graphs or fair access. Enclosure happens above the network: through product design, contracts, defaults and control of data. Changing those rules is possible.', sources:['internet','protocol'] },
  { id:'credit', act:'Enclosure', chapter:'Money’s promise', title:'Money carries\na claim on tomorrow.', body:'In modern banking, a loan creates a deposit—and a debt. Credit can fund a home, a business, a new possibility. Repayment and interest also bring tomorrow’s income into today’s decisions.', scene:1.55, action:'', mechanism:'A new deposit ↔ an obligation to repay', note:'As the Bank of England explains, bank lending creates deposit money; repayment of principal removes it. Lending is constrained by capital, risk, regulation and settlement needs. This does not mean interest makes endless growth mathematically inevitable. Debt creates obligations, not a universal explanation for extraction.', sources:['money'] },
  { id:'growth', act:'Enclosure', chapter:'The growth bargain', title:'Build the network.\nOwn the returns.', body:'Platform expansion met a financial system seeking returns. Investors funded scale before profit. Once people depended on the service, fees, ads, and tighter rules could turn shared activity into private income.', scene:1.80, action:'', mechanism:'Capital → scale → dependence → returns', note:'Venture capital is equity, not bank debt: investors buy ownership and accept the risk of losing their investment. Debt service and shareholder expectations are different pressures. Neither dictates one business model. Here the story makes an argument about their interaction with concentrated platforms, not a law of money or internet architecture.', sources:[] },
  { id:'extraction', act:'The human cost', chapter:'The attention market', title:'Our attention.\nTheir empire.', body:'A pause. A click. One more minute. Advertising turns these traces into predictions about what will hold us. The better the system gets at keeping us here, the more attention it can sell.', scene:2, action:'Trace an exchange', mechanism:'Watch → predict → rank → sell', note:'The FTC’s 2024 study documented extensive data collection and monetization across major social and video services. Ad-funded models can reward engagement and targeting. The gold flowing inward represents captured value; it is not a literal transaction record or a measurement of any one company.', sources:['surveillance'] },
  { id:'psyche', act:'The human cost', chapter:'The inner world', title:'The feed enters\nour inner world.', body:'Comparison follows us home. Interruptions fracture the day. A system tuned for return visits can pull against sleep, attention, and the slow work of belonging. Connection is real. So is the cost of never quite leaving.', scene:2.20, action:'', mechanism:'A person’s rhythm. A platform’s rhythm.', note:'Effects differ across people, platforms and uses. A randomized Facebook deactivation study found improved subjective well-being and more offline activity, but also less factual news knowledge. That result is not a diagnosis of every user or proof that all online connection is harmful.', sources:['wellbeing'] },
  { id:'livelihoods', act:'The human cost', chapter:'Life at the gate', title:'A livelihood\non borrowed ground.', body:'Creators need reach. Shops need discovery. Communities need a place to meet. When one gate controls the way in, a changed ranking or rising fee can reshape a life far beyond the screen.', scene:2.36, action:'', mechanism:'Those who make the value do not always set the terms.', note:'This is the economic risk of dependence on an intermediary. A seller may own their products while a platform controls discovery; a creator may make the work while a platform controls distribution. The illustration shows unequal bargaining power, not a quantitative estimate of platform fees or income loss.', sources:[] },
  { id:'democracy', act:'The human cost', chapter:'The shared world', title:'A public square.\nA private control room.', body:'The same machinery helps decide what becomes visible, whose voice travels, and which conflicts fill the day. Democracy needs shared attention. Its conditions are increasingly shaped by systems the public does not govern.', scene:2.52, action:'', mechanism:'Who sets the conditions for being heard?', note:'Algorithms shape exposure, but polarization has many causes. In a 2023 Facebook experiment, reducing like-minded content did not measurably reduce political polarization. The chapter’s argument concerns private control of public visibility; the divided light is a metaphor, not evidence that algorithms alone divide society.', sources:['politics'] },
  { id:'acceleration', act:'Acceleration', chapter:'The machine eye', title:'The race\ngets a mind.', body:'Now AI can generate the message, predict the response, and repeat the experiment at scale. Put that capacity inside an extraction machine, and the machine gains new ways to reach into our lives.', scene:2.95, action:'', mechanism:'Generate → predict → adapt → repeat', note:'This is a conditional scenario, not an assertion that all AI is used this way. The FTC’s AI partnership study identifies concentration risks around cloud access, contractual commitments and privileged information. AI can also support science, creativity and public benefit. Ownership and incentives help determine the direction.', sources:['ai'] },
  { id:'moloch', act:'Acceleration', chapter:'The race for everything', title:'When enough\nis never enough.', body:'More data. More compute. More territory. Each giant races because the others are racing. This is Moloch: a system that can push its participants to sacrifice the world they all depend on.', scene:3.35, action:'', mechanism:'The pressure to win can outrun the reason to build.', note:'Moloch is a metaphor for destructive competitive incentives, not a literal entity or a theory that firms secretly coordinate. The reaching tendrils dramatize a risk: AI capacity and control of infrastructure reinforcing each other. This future is neither certain nor unavoidable.', sources:['ai'] },
  { id:'choice', act:'A living web', chapter:'The choice', title:'The rules\ncan be remade.', body:'The machine is powerful. It is also made of choices: ownership, funding, protocols, laws. We can limit extraction, share decisions, and build tools whose success depends on helping a community thrive.', scene:3.88, action:'', mechanism:'Change the incentives. Change what grows.', note:'Open technology is one part of the response. Competition policy, privacy protections, public investment, accountable moderation and cooperative ownership address different parts of the problem. The story proposes combining these approaches; no single protocol guarantees a democratic economy.', sources:[] },
  { id:'reconnect', act:'A living web', chapter:'Direct relationships', title:'A different web\nstarts between us.', body:'One connection can go around the middle. Then another. People exchange knowledge, care, and useful things. Value returns to the relationship instead of always flowing away from it.', scene:4.40, action:'Send a spark', mechanism:'Give · receive · share onward', note:'Peer relationships do not require every device to connect directly to every other device. Servers can still help. The goal is to reduce compulsory dependence on one owner and give people meaningful choice over how they connect. The returning light illustrates reciprocity, not a promised financial return.', sources:[] },
  { id:'belong', act:'A living web', chapter:'The freedom to leave', title:'Take your identity.\nKeep your people.', body:'Open protocols can separate a relationship from the app that hosts it. Change your tools. Choose your feed. Carry your identity. A place becomes healthier when staying is a choice.', scene:5.05, action:'', mechanism:'Portable identity · interoperable tools', note:'AT Protocol is one example: it separates hosting, identity and applications in a federated server architecture. It is not device-to-device networking. Successful migration still depends on keys, data and available services. Portability helps make exit possible; it does not eliminate concentration or governance problems.', sources:['protocol'] },
  { id:'stewardship', act:'A living web', chapter:'Belonging takes work', title:'Small enough\nto care for.', body:'A commons needs more than connections. People need shared rules, ways to repair harm, and resources to maintain what they use. Membership, cooperative ownership, and public support can fund care without selling every moment.', scene:5.65, action:'', mechanism:'Shared rules · shared upkeep · a real voice', note:'These are design proposals, not claims that every cooperative succeeds. Communities need budgets, accountable decisions, moderation and safe ways to leave. Different groups can choose different arrangements while remaining able to exchange across their boundaries. The circles represent stewardship rather than new walls.', sources:[] },
  { id:'living', act:'A living web', chapter:'Life beyond the screen', title:'A web in service\nof life.', body:'Tools shared. Gardens tended. Neighbors finding each other. Networks become places: workshops, food cooperatives, ecovillages. Digital coordination supports a richer life together—and knows when to step out of the way.', scene:6.3, action:'Follow the exchange', mechanism:'From connection to community to place', note:'The valley is an imagined possibility. Digital tools do not create housing, ecological restoration or trust by themselves. They can help people coordinate real work, share resources and learn across places. The measure of success is what becomes possible beyond the interface.', sources:[] },
  { id:'future', act:'A living web', chapter:'Techne', title:'The future is\nsomething we make.', body:'Techne is the craft of shaping tools—and choosing what they serve. Let’s build for life.', scene:7, action:'', mechanism:'', note:'This story is an invitation to experiment with tools, institutions and ways of living that strengthen agency and reciprocity. The landscape is metaphorical; the choices are practical.', sources:[] },
];
export const LAST = BEATS.length - 1;
